# Generated by Django 3.2.8 on 2021-12-12 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='profilepic',
        ),
        migrations.AddField(
            model_name='profile',
            name='profilepic',
            field=models.ImageField(blank=True, max_length=144, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
