# Generated by Django 3.2.8 on 2021-11-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestionmodel',
            name='author',
            field=models.CharField(default='hunter', max_length=240),
        ),
    ]
