# Generated by Django 3.2.8 on 2021-12-13 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20211212_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='bio',
        ),
    ]
