# Generated by Django 3.2.8 on 2021-12-12 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_commentmodel_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='bio',
            field=models.TextField(default='Please write a bio here'),
        ),
    ]
