# Generated by Django 3.2.8 on 2021-12-13 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
    ]
